import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Legal Notice / Impressum",
  description: "Furx Legal Notice pursuant to Argentine law + § 5 TMG (DE) + L213-1 (FR) — operator identification details.",
  alternates: { canonical: "https://furx.cloud/imprint/" },
};

export default function ImprintPage() {
  return (
    <LegalLayout title="Legal Notice / Impressum">
      <p>
        Information provided in accordance with § 5 of the German Telemediengesetz (TMG), § 18 of the
        German Medienstaatsvertrag (MStV), Art. L213-1 of the French Code de la consommation, and the
        commercial transparency rules of the Argentine Republic.
      </p>

      <h2>1. Operator</h2>
      <ul>
        <li><strong>Legal name</strong>: INVERSO HUB S.R.L. (Sociedad de Responsabilidad Limitada — limited liability company)</li>
        <li><strong>Trade name</strong>: Furx</li>
        <li><strong>Registered office</strong>: Autonomous City of Buenos Aires, Argentine Republic</li>
        <li><strong>Registration</strong>: Inspección General de Justicia (IGJ), Argentina — registration number available upon request</li>
        <li><strong>CUIT (tax ID)</strong>: registration in progress with the Federal Administration of Public Revenue (AFIP); full number provided in commercial documentation</li>
      </ul>

      <h2>2. Legal representative</h2>
      <ul>
        <li><strong>el autor Inverso</strong> — Managing Partner</li>
      </ul>

      <h2>3. Contact</h2>
      <ul>
        <li>General inquiries: <a href="mailto:hello@furx.cloud">hello@furx.cloud</a></li>
        <li>Support: <a href="mailto:support@furx.cloud">support@furx.cloud</a></li>
        <li>Legal: <a href="mailto:legal@furx.cloud">legal@furx.cloud</a></li>
        <li>Privacy / DPO: <a href="mailto:dpo@furx.cloud">dpo@furx.cloud</a></li>
        <li>Security: <a href="mailto:security@furx.cloud">security@furx.cloud</a></li>
      </ul>
      <p>
        Specific postal address for formal notices: available upon request by writing to{" "}
        <a href="mailto:legal@furx.cloud">legal@furx.cloud</a>.
      </p>

      <h2>4. Sites and services</h2>
      <ul>
        <li>Public site: <a href="https://furx.cloud">https://furx.cloud</a></li>
        <li>Customer dashboard: <a href="https://app.furx.cloud">https://app.furx.cloud</a></li>
        <li>Status: <a href="https://status.furx.cloud">https://status.furx.cloud</a></li>
        <li>Apache-2.0 repository: <a href="https://github.com/hernaninverso/furx">github.com/hernaninverso/furx</a></li>
      </ul>

      <h2>5. Billing · Merchant of Record</h2>
      <p>
        Subscription payments are collected through <strong>Paddle.com Market
        Limited</strong> acting as Merchant of Record (MoR). Paddle issues invoices in its
        own name and handles applicable taxes.
      </p>
      <ul>
        <li>Paddle.com Market Ltd. · Judd House, 18-29 Mora Street, London, EC1V 8BT, United Kingdom</li>
        <li>UK VAT: GB117 4170 06</li>
      </ul>

      <h2>6. Business activity</h2>
      <p>
        INVERSO HUB S.R.L. is a limited liability company incorporated under the General
        Companies Law No. 19,550 of the Argentine Republic, engaged in the development and
        operation of software platforms for development professionals.
      </p>

      <h2>7. Nature of the Furx product</h2>
      <p>
        <strong>Furx is NOT a provider of language models.</strong> Furx is a local
        developer productivity tool that orchestrates calls to third-party LLM providers
        using credentials supplied by the User (BYOK — Bring Your Own
        Keys). INVERSO HUB assumes no responsibility for:
      </p>
      <ul>
        <li>The quality, accuracy, biases, or consequences of outputs generated by third-party LLM models.</li>
        <li>Decisions the User makes based on those outputs.</li>
        <li>The User&apos;s compliance with the TOS of the LLM providers they use (Anthropic, OpenAI, Google, etc.).</li>
        <li>The configuration state of the User&apos;s local environment (OS, drivers, Ollama, etc.).</li>
      </ul>

      <h2>8. Intellectual property</h2>
      <ul>
        <li>The <strong>Furx</strong> trademark, the logo (coral F icon), and the visual identity are the property of INVERSO HUB S.R.L., protected by Trademark and Designations Law No. 22,362 of the Argentine Republic and applicable international treaties.</li>
        <li>The software core is distributed under the Apache-2.0 license; see{" "}
          <a href="https://github.com/hernaninverso/furx/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">LICENSE</a>.</li>
        <li>The commercial features and license-gating code are protected by Law No. 11,723.</li>
      </ul>

      <h2>9. Jurisdiction</h2>
      <p>
        For users domiciled in Argentina, commercial relations are governed by Argentine law
        and subject to the jurisdiction of the ordinary commercial courts of the City of Buenos Aires. For
        users outside Argentina, see Clause 16 of the <a href="/terms/">Terms</a>.
      </p>

      <h2>10. Online dispute resolution (EU)</h2>
      <p>
        The European online dispute resolution (ODR) platform is available at{" "}
        <a href="https://ec.europa.eu/consumers/odr/" target="_blank" rel="noopener noreferrer">
          ec.europa.eu/consumers/odr/
        </a>. We are neither obliged nor willing to participate in proceedings before a consumer
        arbitration body.
      </p>

      <h2>11. Notice regarding the right of withdrawal (EU consumers)</h2>
      <p>
        Pursuant to Directive 2011/83/EU, consumers residing in the EU have{" "}
        <strong>14 days</strong> from the conclusion of the contract to withdraw without
        stating reasons, in accordance with our <a href="/refund/">Refund Policy</a>.
      </p>

      <h2>12. Third-party links</h2>
      <p>
        This site links to third-party services (GitHub, Paddle, Cloudflare, LLM providers,
        Tauri). INVERSO HUB is not responsible for the content, availability, or privacy
        practices of those services.
      </p>
    </LegalLayout>
  );
}
