#!/bin/bash
# setup-account.sh — universal CLI account onboarding (Codex / Gemini / Aider / OpenAI / Custom).
# For Claude Max OAuth, use setup-max-account.sh (browser-redirect flow).
#
# Usage:
#   setup-account.sh <slug> --cli <kind>
#     kind: codex | gemini | aider | openai-api | custom

set -euo pipefail

SLUG=""
KIND=""

while [ $# -gt 0 ]; do
  case "$1" in
    --cli) KIND="${2:-}"; shift 2 ;;
    --cli=*) KIND="${1#--cli=}"; shift ;;
    -h|--help)
      cat <<'EOF'
Usage:  setup-account.sh <slug> --cli <kind>

  Adds a CLI account (non-Claude) to macOS Keychain. The slug becomes the wrapper
  name ~/bin/<kind>-as-<slug> that exports the right env var when you run the CLI.

  kind:
    codex        env CODEX_API_KEY / OPENAI_API_KEY
    gemini       env GEMINI_API_KEY
    aider        env ANTHROPIC_API_KEY (or another provider key)
    openai-api   env OPENAI_API_KEY
    custom       env API_KEY (or pass --env-var NAME)

  For Claude Max accounts use setup-max-account.sh (browser OAuth flow).
EOF
      exit 0
      ;;
    --env-var) ENV_VAR_OVERRIDE="${2:-}"; shift 2 ;;
    -*) echo "ERROR: unknown flag $1" >&2; exit 2 ;;
    *)
      if [ -z "$SLUG" ]; then SLUG="$1"; else echo "ERROR: extra arg $1" >&2; exit 2; fi
      shift
      ;;
  esac
done

if [ -z "$SLUG" ] || [ -z "$KIND" ]; then
  echo "Usage: setup-account.sh <slug> --cli <codex|gemini|aider|openai-api|custom>" >&2
  exit 1
fi

if [[ ! "$SLUG" =~ ^[A-Za-z0-9_-]{1,32}$ ]]; then
  echo "ERROR: invalid slug '$SLUG' (allowed: [A-Za-z0-9_-]{1,32})" >&2
  exit 2
fi

# Codex MED fix B9.1: validate --env-var override before interpolating into wrapper/SQL.
# Must match POSIX env var name conventions to avoid shell + SQL injection vectors.
if [ -n "${ENV_VAR_OVERRIDE:-}" ]; then
  if [[ ! "$ENV_VAR_OVERRIDE" =~ ^[A-Z_][A-Z0-9_]{0,63}$ ]]; then
    echo "ERROR: invalid --env-var '$ENV_VAR_OVERRIDE' (must match ^[A-Z_][A-Z0-9_]*$, max 64)" >&2
    exit 2
  fi
fi

case "$KIND" in
  codex)       ENV_VAR="${ENV_VAR_OVERRIDE:-OPENAI_API_KEY}";     SVC_PREFIX="codex-cli-" ;;
  gemini)      ENV_VAR="${ENV_VAR_OVERRIDE:-GEMINI_API_KEY}";     SVC_PREFIX="gemini-cli-" ;;
  aider)       ENV_VAR="${ENV_VAR_OVERRIDE:-ANTHROPIC_API_KEY}";  SVC_PREFIX="aider-" ;;
  openai-api)  ENV_VAR="${ENV_VAR_OVERRIDE:-OPENAI_API_KEY}";     SVC_PREFIX="openai-api-" ;;
  custom)      ENV_VAR="${ENV_VAR_OVERRIDE:-API_KEY}";            SVC_PREFIX="custom-" ;;
  *)
    echo "ERROR: unknown --cli '$KIND' (codex|gemini|aider|openai-api|custom)" >&2
    exit 2
    ;;
esac

SERVICE="${SVC_PREFIX}${SLUG}"
WRAPPER="${HOME}/bin/${KIND}-as-${SLUG}"

cat <<EOF

  ┌─ Furx · Add CLI account (${KIND}) ───────────────────────────────┐

    Slug:        ${SLUG}
    CLI:         ${KIND}
    Env var:     ${ENV_VAR}
    Keychain:    ${SERVICE}
    Wrapper:     ~/bin/${KIND}-as-${SLUG}

EOF

# Hint per kind on dónde obtener el token
case "$KIND" in
  codex)
    cat <<EOF
    Pegá una API key de OpenAI (https://platform.openai.com/api-keys).
    Si usás Codex CLI con ChatGPT Plus OAuth → no necesitás API key
    aparte; corré 'codex login' y dejá esa cuenta activa.

EOF
    ;;
  gemini)
    cat <<EOF
    Obtené API key en https://aistudio.google.com/apikey

EOF
    ;;
  aider)
    cat <<EOF
    Aider lee env vars: ANTHROPIC_API_KEY (default acá), OPENAI_API_KEY, etc.
    Si querés otra, pasá --env-var OTRO_NOMBRE.
    Token de Anthropic: https://console.anthropic.com/settings/keys

EOF
    ;;
  openai-api)
    cat <<EOF
    Token OpenAI: https://platform.openai.com/api-keys

EOF
    ;;
  custom)
    cat <<EOF
    Pegá la API key. Wrapper exportará ${ENV_VAR}.
    Para cambiar el nombre del env var: --env-var TU_VAR

EOF
    ;;
esac

# Overwrite check
if security find-generic-password -a "$USER" -s "$SERVICE" -w >/dev/null 2>&1; then
  echo "  [!] Keychain '${SERVICE}' YA existe — continuar lo SOBREESCRIBE."
  read -r -p "  Continuar? (y/N) " ans
  ans_lower=$(echo "${ans:-}" | tr '[:upper:]' '[:lower:]')
  if [ "$ans_lower" != "y" ]; then
    echo "  Abortado."; exit 0
  fi
fi

echo "  Pegá el token / API key (input oculto):"
read -r -s -p "  > " TOKEN
echo

if [ -z "$TOKEN" ]; then
  echo "  ERROR: token vacío." >&2
  exit 1
fi
if [ ${#TOKEN} -lt 16 ]; then
  echo "  ERROR: token sospechosamente corto (${#TOKEN} chars)." >&2
  exit 1
fi

NOTE="${KIND} CLI account · slug ${SLUG} · env ${ENV_VAR} · $(date -u +%Y-%m-%d)"
security add-generic-password -U -a "$USER" -s "$SERVICE" -j "$NOTE" -w "$TOKEN"
TOKEN=""

# Create wrapper
if [ ! -f "$WRAPPER" ]; then
  cat > "$WRAPPER" <<EOFW
#!/bin/bash
# Auto-generated by setup-account.sh
TOKEN=\$(security find-generic-password -a "\$USER" -s "${SERVICE}" -w 2>/dev/null) || {
  echo "ERROR: no Keychain entry '${SERVICE}' for user \$USER" >&2
  echo "       run: ~/bin/setup-account.sh ${SLUG} --cli ${KIND}" >&2
  exit 1
}
export ${ENV_VAR}="\$TOKEN"
TOKEN=""
exec ${KIND} "\$@"
EOFW
  chmod +x "$WRAPPER"
  echo "  Wrapper creado: $WRAPPER"
fi

# Auto-register en (Furx) DB (claude_accounts table — sigue siendo el storage universal)
# Gemini MED fix B9.1: defensive — SLUG/KIND/ENV_VAR/SERVICE están todos validados arriba,
# pero LABEL_DEFAULT lo seteo yo (no user-provided acá) y solo contiene KIND + SLUG que ya
# fueron validados con regex estricto. Cero single-quote / control chars posibles.
FURX_DB="${HOME}/.furx/furx.db"
if [ -f "$FURX_DB" ] && command -v sqlite3 >/dev/null 2>&1; then
  NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  LABEL_DEFAULT="${KIND} ${SLUG}"  # safe: ambos passados regex [A-Za-z0-9_-]{1,32}
  STORAGE_SLUG="${KIND}:${SLUG}"
  # Use parameter binding via bind values when possible — sqlite3 CLI lo permite via .param set
  # pero el script ya valida cada interpolación con regex.
  sqlite3 "$FURX_DB" <<SQL 2>/dev/null \
    && echo "  [OK] (Furx) DB:    cuenta '${KIND}/${SLUG}' registrada" \
    || echo "  [WARN] (Furx) DB:  no se pudo registrar (agregala en Furx Connect tab)"
INSERT INTO claude_accounts
  (slug, cli_kind, label, browser, status, env_var, keychain_service,
   last_verified_at, created_at, updated_at)
VALUES
  ('${STORAGE_SLUG}', '${KIND}', '${LABEL_DEFAULT}', NULL, 'verified',
   '${ENV_VAR}', '${SERVICE}', '${NOW}', '${NOW}', '${NOW}')
ON CONFLICT(slug) DO UPDATE SET
  status = 'verified',
  env_var = excluded.env_var,
  keychain_service = excluded.keychain_service,
  last_verified_at = excluded.last_verified_at,
  updated_at = excluded.updated_at;
SQL
fi

cat <<EOF

  [OK] Keychain: ${SERVICE}
  [OK] Wrapper:  ${WRAPPER}

  Probar:
      ${WRAPPER} --help

  En Furx, el pane dropdown ahora ofrece '${KIND} · ${LABEL_DEFAULT}'.

EOF
